title: Zach Griebel Portfolio
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: Zach Griebel
avatar: /zg_profile.png
email: zgriebel11@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: zgriebz23
  card: summary
logo: logo.png
social:
  name: Shangzhi Huang
  links:
    - https://twitter.com/zgriebz23
    - https://github.com/zgriebel
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
